version: '3.9'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: tonhelp
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    external: false
