version: '3.9'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: tonhelp
    ports:
      - 5432:5432
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net1
  bot:
    image: ${DOCKER_REGISTRY:-localhost:5000}/ton-vs-bot:v0.2
    build:
      context: ton-vs-bot
      dockerfile: Dockerfile
    secrets:
      - postgres_password
      - telegram_token
    networks:
      - net1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
  daily-stats:
    image: ${DOCKER_REGISTRY:-localhost:5000}/ton-vs-bot-daily-stat:v0.2
    build:
      context: ton-vs-daily-stat-bot
      dockerfile: Dockerfile
    secrets:
      - postgres_password
      - stats_telegram_token
    networks:
      - net1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
volumes:
  postgres_data:
    external: false
networks:
  net1:
secrets:
  postgres_password:
    file: private/postgres_password
  telegram_token:
    file: private/telegram_token
  stats_telegram_token:
    file: private/stats_telegram_token
