version: '3.9'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: tonhelp
    ports:
      - 5432:5432
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net1
  bot:
    image: localhost:5000/ton-vs-bot:latest
    build:
      context: ton-vs-bot
      dockerfile: Dockerfile
    secrets:
      - postgres_password
      - telegram_token
    networks:
      - net1
volumes:
  postgres_data:
    external: false
networks:
  net1:
secrets:
  postgres_password:
    file: private/postgres_password
  telegram_token:
    file: private/telegram_token
